import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed left-2 top-2 bottom-2 w-52 rounded-md bg-gray-200 p-5 z-[1000] dark:bg-gray-800">
          <Link href="/">
            <Image src="icon.svg" width={50} height={50} alt="anti 67" className="block dark:hidden" />
            <Image src="icon-dark.svg" width={50} height={50} alt="anti 67" className="hidden dark:block" />
          </Link>
          <Link href="/anti-67-clicker" className="mt-4 block hover:underline">
            Anti-67 Clicker
          </Link>
          <Link href="/67-sanitizer" className="mt-2 block hover:underline">
            67 Sanitizer
          </Link>
        </div>

        <div className="ml-60 p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
